In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder

df = pd.read_csv("cisco_firewall_final_dataset_with_severity.csv")

BASIC VALIDATION

In [2]:
print("Dataset Shape:", df.shape)

Dataset Shape: (80, 18)

In [3]:
print("Missing Values:\n", df.isnull().sum())

Missing Values:
 model_series              0
model_sku                 0
cpu_util_avg              0
memory_util_avg           0
port_util_avg             0
interface_error_rate      0
connection_rate_cps       0
syn_flood_events          0
inspection_drop_rate      0
fragmented_packet_pct     0
ssl_decrypt_enabled       0
image_upgrade_count       0
reboot_count              0
failover_events           0
core_file_count           0
core_file_flag            0
device_stability_score    0
severity_level            0
dtype: int64

In [4]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

PREPROCESSING FOR ML

In [5]:
df_prep = df.copy()

In [6]:
# Encode severity
severity_encoder = LabelEncoder()
df_prep["severity_encoded"] = severity_encoder.fit_transform(df_prep["severity_level"])

In [7]:
# One-hot encode model_sku
df_prep = pd.get_dummies(df_prep, columns=["model_sku"], drop_first=True)

In [8]:

# Feature scaling
scale_cols = [
    "cpu_util_avg","memory_util_avg","port_util_avg","interface_error_rate",
    "connection_rate_cps","syn_flood_events","inspection_drop_rate",
    "fragmented_packet_pct","image_upgrade_count","reboot_count","failover_events",
    "core_file_count","device_stability_score"
]

scaler = StandardScaler()
df_prep[scale_cols] = scaler.fit_transform(df_prep[scale_cols])

In [9]:
# Drop original severity
df_prep.drop(columns=["severity_level"], inplace=True)

In [12]:
# Save preprocessed dataset
df_prep.to_csv("cisco_firewall_preprocessed_dataset.csv", index=False)
df_prep

,model_series,cpu_util_avg,memory_util_avg,port_util_avg,interface_error_rate,connection_rate_cps,syn_flood_events,inspection_drop_rate,fragmented_packet_pct,ssl_decrypt_enabled,...,reboot_count,failover_events,core_file_count,core_file_flag,device_stability_score,severity_encoded,model_sku_A1M,model_sku_A2H,model_sku_A2L,model_sku_A2M
0,260,-1.363345,1.259906,1.289599,0.172967,-0.839855,1.336207,-1.414355,1.353863,1,...,0.362031,0.544331,1.418510,1,-0.764169,0,0,0,0,1
1,220,-0.525063,1.565812,-1.501731,-1.420899,-1.196440,-1.617057,-1.863179,-1.235555,0,...,0.362031,-0.362887,-1.994447,0,2.396785,0,0,0,0,0
2,260,1.443924,1.032255,0.288059,1.026611,-1.179300,-0.864264,-1.635027,-0.553951,0,...,-0.820110,1.451549,-0.287968,1,-0.764169,0,0,1,0,0
3,260,-0.823986,0.612523,-0.166344,1.056458,-1.365597,-0.458914,0.672674,-0.582704,1,...,-0.229040,-1.270106,0.565271,1,-0.764169,0,0,1,0,0
4,220,0.514666,0.299503,0.589448,0.363992,0.686824,1.509929,0.081723,-1.357330,0,...,-0.229040,0.544331,-0.287968,1,-0.764169,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,240,0.703117,0.470242,1.475070,-1.080635,-1.049195,-1.037985,-0.613953,-0.011036,1,...,-1.411180,0.544331,-1.141208,0,0.523024,0,0,0,0,1
76,240,1.229480,-1.073517,1.224685,-0.459803,-0.866279,0.120157,-1.795855,0.775430,1,...,-0.229040,1.451549,-0.287968,1,-0.487178,0,0,0,0,1
77,260,1.261972,-1.514590,0.473529,1.313148,0.820400,0.178064,0.137826,1.106930,1,...,-0.229040,-0.362887,1.418510,1,-0.764169,0,0,0,0,1
78,260,-0.356107,-0.354993,1.011394,-1.355234,1.529637,0.583414,0.081723,0.760208,0,...,0.362031,-0.362887,-1.141208,0,1.207354,0,1,0,0,0
79,240,1.372443,-1.585731,0.607995,-0.041936,-0.126967,0.235972,-0.584032,0.139492,1,...,-0.229040,0.544331,1.418510,1,-0.764169,0,0,0,1,0

In [11]:
# PREPROCESSING VERIFICATION

print("\nPreprocessed dataset shape:", df_prep.shape)
print("Severity mapping:", dict(zip(severity_encoder.classes_, severity_encoder.transform(severity_encoder.classes_))))
df_prep

Preprocessed dataset shape: (80, 21)
Severity mapping: {'High': 0}

,model_series,cpu_util_avg,memory_util_avg,port_util_avg,interface_error_rate,connection_rate_cps,syn_flood_events,inspection_drop_rate,fragmented_packet_pct,ssl_decrypt_enabled,...,reboot_count,failover_events,core_file_count,core_file_flag,device_stability_score,severity_encoded,model_sku_A1M,model_sku_A2H,model_sku_A2L,model_sku_A2M
0,260,-1.363345,1.259906,1.289599,0.172967,-0.839855,1.336207,-1.414355,1.353863,1,...,0.362031,0.544331,1.418510,1,-0.764169,0,0,0,0,1
1,220,-0.525063,1.565812,-1.501731,-1.420899,-1.196440,-1.617057,-1.863179,-1.235555,0,...,0.362031,-0.362887,-1.994447,0,2.396785,0,0,0,0,0
2,260,1.443924,1.032255,0.288059,1.026611,-1.179300,-0.864264,-1.635027,-0.553951,0,...,-0.820110,1.451549,-0.287968,1,-0.764169,0,0,1,0,0
3,260,-0.823986,0.612523,-0.166344,1.056458,-1.365597,-0.458914,0.672674,-0.582704,1,...,-0.229040,-1.270106,0.565271,1,-0.764169,0,0,1,0,0
4,220,0.514666,0.299503,0.589448,0.363992,0.686824,1.509929,0.081723,-1.357330,0,...,-0.229040,0.544331,-0.287968,1,-0.764169,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,240,0.703117,0.470242,1.475070,-1.080635,-1.049195,-1.037985,-0.613953,-0.011036,1,...,-1.411180,0.544331,-1.141208,0,0.523024,0,0,0,0,1
76,240,1.229480,-1.073517,1.224685,-0.459803,-0.866279,0.120157,-1.795855,0.775430,1,...,-0.229040,1.451549,-0.287968,1,-0.487178,0,0,0,0,1
77,260,1.261972,-1.514590,0.473529,1.313148,0.820400,0.178064,0.137826,1.106930,1,...,-0.229040,-0.362887,1.418510,1,-0.764169,0,0,0,0,1
78,260,-0.356107,-0.354993,1.011394,-1.355234,1.529637,0.583414,0.081723,0.760208,0,...,0.362031,-0.362887,-1.141208,0,1.207354,0,1,0,0,0
79,240,1.372443,-1.585731,0.607995,-0.041936,-0.126967,0.235972,-0.584032,0.139492,1,...,-0.229040,0.544331,1.418510,1,-0.764169,0,0,0,1,0